# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r}
unzip('activity.zip')
data <- read.csv('activity.csv', header=TRUE, 
  colClasses = c('numeric', 'character', 'numeric'))
```
## What is mean total number of steps taken per day?

```{r}
library(reshape2)
date_data <- melt(data[,c('steps', 'date')], id = c('date'))
date_steps <- dcast(date_data, date ~ variable, sum)
library(ggplot2)
qplot(steps, data=date_steps)
```

```{r}
mean(date_steps$steps, na.rm=TRUE)
median(date_steps$steps, na.rm=TRUE)
```

## What is the average daily activity pattern?

```{r}
interval_data <- melt(data[, c('steps', 'interval')], id = c('interval')) 
interval_steps <- dcast(interval_data, interval ~ variable, mean, na.rm = TRUE)
qplot(interval, steps, data = interval_steps, geom='line')
```

```{r}
interval_steps[which.max(interval_steps[, c('steps')]),]$interval
```

## Imputing missing values

```{r}
sum(is.na(data$steps))
```

```{r}
library(plyr)
setMissingSteps <- function(data) {
  if (is.na(data$steps)) {
    data$steps <- interval_steps[interval_steps$interval == data$interval, ]$steps
  }
  data
}
data_without_missing <- adply(data, 1, setMissingSteps)
```

```{r}
date_nomissing_data <- melt(data_without_missing[,c('steps', 'date')], id = c('date'))
date_nomissing_steps <- dcast(date_nomissing_data, date ~ variable, sum)
qplot(steps, data=date_nomissing_steps)
```

```{r}
mean(date_nomissing_steps$steps)
median(date_nomissing_steps$steps)
```


## Are there differences in activity patterns between weekdays and weekends?

```{r}
data_without_missing$dayofweek <- as.POSIXlt(data_without_missing$date)$wday
data_without_missing$dayofweek <- sapply(data_without_missing$dayofweek, 
                                         function(day) {
                                           if (day == 0 || day == 6) {
                                             'weekend'
                                           } else {
                                             'weekday'
                                           }
                                         }
                                        )
data_without_missing$dayofweek <- as.factor(data_without_missing$dayofweek)

meltdata <- melt(data_without_missing[,c('steps', 'interval', 'dayofweek')], 
                 id = c('dayofweek','interval'))
plotdata <- dcast(meltdata, interval + dayofweek ~ variable, mean)

g <- ggplot(plotdata, aes(interval, steps))
g + geom_line() + facet_grid(dayofweek ~ .) + 
  labs(y = 'Number of steps') + labs(x = 'Interval')
```